// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shlabdnmjqeypmmyzbja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNobGFiZG5tanFleXBtbXl6YmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODMzMDgsImV4cCI6MjA1Nzk1OTMwOH0.hlhz9cADTOePOUD9Brx4Pdw2RUjbqf7Wbc7raGzjEtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);